### PR TITLE
Add support for Silverstripe 5

### PR DESCRIPTION
**Pull request by MelissaWu-SS**
- Specify the required PHP version
- Change the required version for `dnadesign/silverstripe-elemental` from to `^5`
- Change the required version for `silverstripe/vendor-plugin` from to `^2`

### CODE REVIEW

**Review by chrispenny — CHANGES_REQUESTED** [review]
Thanks, @MelissaWu-SS !

I wanted to get Github Actions into `master` before we made this change so that we were testing against SS4 and (with your changes) SS5. I think you'll need to rebase your branch.

For reference:
https://github.com/dnadesign/silverstripe-elemental-list/pull/31

**Comment by MelissaWu-SS** [comment]
@chrispenny Thanks for the review and comments! I've just pushed the change, could you please check it?🙏

**Comment by MelissaWu-SS** [comment]
> @chrispenny Thanks for the review and comments! I've just pushed the change, could you please check it?🙏

Sorry, just realise there is a check fail I need to fix.

**Comment by MelissaWu-SS** [comment]
> > @chrispenny Thanks for the review and comments! I've just pushed the change, could you please check it?🙏
> 
> Sorry, just realise there is a check fail I need to fix.

Checks passed now!

**Review by chrispenny — APPROVED** [review]

**Pull request merged**
